export const shirtList = [
  {
    id: "1000",
    name: "Plain Shirt",
    type: "shirts",
    color: "black",
    icon: "tshirt",
    margin: "20px",
    imgHeight: "220px",
    imgWidth: "210px",
    sizes: ["xs", "sm", "md", "lg", "xl"],
    price: "$15.00",
    msg: "NEW",
  },
  {
    id: "1001",
    name: "Plain Shirt",
    type: "shirts",
    color: "white",
    icon: "tshirt",
    margin: "20px",
    imgHeight: "220px",
    imgWidth: "210px",
    sizes: ["xs", "sm", "md", "lg", "xl"],
    price: "$10.00",
    msg: "SALE",
  },
  {
    id: "1002",
    name: "Plain Shirt",
    type: "shirts",
    color: "red",
    icon: "tshirt",
    margin: "20px",
    imgHeight: "220px",
    imgWidth: "210px",
    sizes: ["xs", "sm", "md", "lg", "xl"],
    price: "$15.00",
    msg: "",
  },
  {
    id: "1003",
    name: "Plain Shirt",
    type: "shirts",
    color: "blue",
    icon: "tshirt",
    margin: "20px",
    imgHeight: "220px",
    imgWidth: "210px",
    sizes: ["xs", "sm", "md", "lg", "xl"],
    price: "$15.00",
    msg: "",
  },
];

export const pantsList = [
  {
    id: "2100",
    name: "Joggers",
    type: "pants",
    color: "black",
    icon: "joggers",
    margin: "45px",
    imgHeight: "190px",
    imgWidth: "140px",
    sizes: [],
    price: "$25.00",
    msg: "NEW",
  },
  {
    id: "2000",
    name: "Long Pants",
    type: "pants",
    color: "khaki",
    icon: "pants-long",
    margin: "50px",
    imgHeight: "190px",
    imgWidth: "140px",
    sizes: [],
    price: "$30.00",
    msg: "",
  },
  {
    id: "2001",
    name: "Long Pants",
    type: "pants",
    color: "blue",
    icon: "pants-long",
    margin: "50px",
    imgHeight: "190px",
    imgWidth: "140px",
    sizes: [],
    price: "$30.00",
    msg: "",
  },
  {
    id: "2200",
    name: "Shorts",
    type: "pants",
    color: "black",
    icon: "pants-short",
    margin: "45px",
    imgHeight: "190px",
    imgWidth: "190px",
    sizes: [],
    price: "$20.00",
    msg: "",
  },
  {
    id: "2201",
    name: "Shorts",
    type: "pants",
    color: "blue",
    icon: "pants-short",
    margin: "45px",
    imgHeight: "190px",
    imgWidth: "190px",
    sizes: [],
    price: "$20.00",
    msg: "",
  },
];

export const accessoriesList = [
  {
    id: "3000",
    name: "Adventurer Hat",
    type: "accessories",
    color: "black",
    icon: "indianajones",
    imgWidth: "220px",
    sizes: [],
    price: "$45.00",
    msg: "NEW",
  },
  {
    id: "3001",
    name: "Socks",
    type: "accessories",
    color: "black",
    icon: "socks",
    margin: "50px",
    imgHeight: "190px",
    imgWidth: "190px",
    sizes: [],
    price: "$2.00",
    msg: "SALE",
  },
  {
    id: "3002",
    name: "Belt",
    type: "accessories",
    color: "black",
    icon: "belt",
    margin: "30px",
    imgHeight: "220px",
    imgWidth: "220px",
    sizes: [],
    price: "$18.50",
    msg: "",
  },
  {
    id: "3003",
    name: "Watch",
    type: "accessories",
    color: "black",
    icon: "watch",
    margin: "70px",
    imgHeight: "150px",
    imgWidth: "150px",
    sizes: [],
    price: "$65.00",
    msg: "",
  },
];
