export const shirtList = [
  {
    name: "Plain Shirt",
    type: "shirts",
    color: "white",
    icon: "tshirt",
    imgHeight: "220px",
    imgWidth: "210px",
    sizes: ["xs", "sm", "md", "lg", "xl"],
    msg: "",
  },
  {
    name: "Plain Shirt",
    type: "shirts",
    color: "black",
    icon: "tshirt",
    imgHeight: "220px",
    imgWidth: "210px",
    sizes: ["xs", "sm", "md", "lg", "xl"],
    msg: "",
  },
  {
    name: "Plain Shirt",
    type: "shirts",
    color: "red",
    icon: "tshirt",
    imgHeight: "220px",
    imgWidth: "210px",
    sizes: ["xs", "sm", "md", "lg", "xl"],
    msg: "",
  },
  {
    name: "Plain Shirt",
    type: "shirts",
    color: "blue",
    icon: "tshirt",
    imgHeight: "220px",
    imgWidth: "210px",
    sizes: ["xs", "sm", "md", "lg", "xl"],
    msg: "",
  },
];

export const pantsList = [
  {
    name: "Joggers",
    type: "pants",
    color: "black",
    icon: "joggers",
    margin: "25px",
    imgHeight: "190px",
    imgWidth: "140px",
    sizes: [],
    msg: "",
  },
  {
    name: "Long Pants",
    type: "pants",
    color: "khaki",
    icon: "pants-long",
    margin: "25px",
    imgHeight: "190px",
    imgWidth: "140px",
    sizes: [],
    msg: "",
  },
  {
    name: "Long Pants",
    type: "pants",
    color: "blue",
    icon: "pants-long",
    margin: "25px",
    imgHeight: "190px",
    imgWidth: "140px",
    sizes: [],
    msg: "",
  },
  {
    name: "Shorts",
    type: "pants",
    color: "black",
    icon: "pants-short",
    imgHeight: "190px",
    imgWidth: "190px",
    sizes: [],
    msg: "",
  },
  {
    name: "Shorts",
    type: "pants",
    color: "blue",
    icon: "pants-short",
    imgHeight: "190px",
    imgWidth: "190px",
    sizes: [],
    msg: "",
  },
  {
    name: "Shorts",
    type: "pants",
    color: "khaki",
    icon: "pants-short",
    imgHeight: "190px",
    imgWidth: "190px",
    sizes: [],
    msg: "",
  },
];

export const accessoriesList = [
  {
    name: "Adventurer Hat",
    type: "accessory",
    color: "black",
    icon: "indianajones",
    imgWidth: "220px",
    sizes: [],
    msg: "",
  },
  {
    name: "Belt",
    type: "accessory",
    color: "black",
    icon: "belt",
    imgHeight: "220px",
    imgWidth: "220px",
    sizes: [],
    msg: "",
  },
  {
    name: "Socks",
    type: "accessory",
    color: "black",
    icon: "socks",
    margin: "25px",
    imgHeight: "190px",
    imgWidth: "190px",
    sizes: [],
    msg: "",
  },
  {
    name: "Watch",
    type: "accessory",
    color: "black",
    icon: "watch",
    margin: "45px",
    imgHeight: "150px",
    imgWidth: "150px",
    sizes: [],
    msg: "",
  },
];
